### ISSUE TITLE
Rename of internal slack channels has broken some nightly runs

### ISSUE THREAD

**Issue by chelnak** [puppetlabs/content-and-tooling-team#48]
# Context

We recently renamed a few slack channels so that they are in line with our new team name. It would appear that this has broken any acceptance test run that has the `Post Workflow Status To Slack` step.

Some questions:

- [ ] Is this step present across the whole module estate?
- [ ] Do we actually need it as we should be looking at other tooling to spot failures

If the outcome is that we would like to keep the functionality, it should be fixed to prevent more false negatives. Otherwise we should remove it from the workflow jobs.

**Comment by david22swan** [comment]
PR to change the slack channel set by default in the templates has been merged. Once applied this template change will redirect the nightly run results to the correct channel:

- https://github.com/puppetlabs/pdk-templates/pull/470

**Comment by david22swan** [comment]
Template changes have been brought into our modules by the following PRs:
1. https://github.com/puppetlabs/puppetlabs-accounts/pull/408
2. https://github.com/puppetlabs/puppetlabs-acl/pull/257
3. https://github.com/puppetlabs/puppetlabs-apache/pull/2234
4. https://github.com/puppetlabs/puppetlabs-apt/pull/1030
5. https://github.com/puppetlabs/puppetlabs-chocolatey/pull/289
6. https://github.com/puppetlabs/puppetlabs-concat/pull/735
7. https://github.com/puppetlabs/puppetlabs-docker/pull/824
8. https://github.com/puppetlabs/puppetlabs-dsc_lite/pull/200
9. https://github.com/puppetlabs/puppetlabs-exec/pull/193
10. https://github.com/puppetlabs/puppetlabs-facter_task/pull/193
11. https://github.com/puppetlabs/puppetlabs-firewall/pull/1047
12. https://github.com/puppetlabs/puppetlabs-haproxy/pull/517
13. https://github.com/puppetlabs/puppetlabs-helm/pull/169
14. https://github.com/puppetlabs/puppetlabs-ibm_installation_manager/pull/205
15. https://github.com/puppetlabs/puppetlabs-iis/pull/343
16. https://github.com/puppetlabs/puppetlabs-inifile/pull/477
17. https://github.com/puppetlabs/puppetlabs-java/pull/515
18. https://github.com/puppetlabs/puppetlabs-java_ks/pull/398
19. https://github.com/puppetlabs/puppetlabs-kubernetes/pull/556
20. https://github.com/puppetlabs/puppetlabs-motd/pull/440
21. https://github.com/puppetlabs/puppetlabs-mysql/pull/1467
22. https://github.com/puppetlabs/puppetlabs-ntp/pull/643
23. https://github.com/puppetlabs/puppetlabs-package/pull/282
24. https://github.com/puppetlabs/puppetlabs-panos/pull/136
25. https://github.com/puppetlabs/puppetlabs-postgresql/pull/1339
26. https://github.com/puppetlabs/puppetlabs-powershell/pull/376
27. https://github.com/puppetlabs/puppetlabs-puppet_conf/pull/172
28. https://github.com/puppetlabs/puppetlabs-reboot/pull/322
29. https://github.com/puppetlabs/puppetlabs-registry/pull/263
30. https://github.com/puppetlabs/puppetlabs-satellite_pe_tools/pull/178
31. https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/209
32. https://github.com/puppetlabs/puppetlabs-service/pull/213
33. https://github.com/puppetlabs/puppetlabs-sqlserver/pull/401
34. https://github.com/puppetlabs/puppetlabs-stdlib/pull/1234
35. https://github.com/puppetlabs/puppetlabs-tagmail/pull/238
36. https://github.com/puppetlabs/puppetlabs-tomcat/pull/488
37. https://github.com/puppetlabs/puppetlabs-vcsrepo/pull/537
38. https://github.com/puppetlabs/puppetlabs-vsphere/pull/230
39. https://github.com/puppetlabs/puppetlabs-websphere_application_server/pull/246

**Comment by david22swan** [comment]
Slack channel has been updated across all supported modules
