### ISSUE TITLE
Certify Kubernetes

### ISSUE THREAD

**Issue by Aaron-Rob** [puppetlabs/content-and-tooling-team#56]
We’re very pleased that your product was included in our v1.21 Certified Kubernetes offerings. However, unless you have acquired a newer certification for your product, puppetlabs-kubernetes, your Kubernetes v1.21 certification will expire in May. Any previous certifications you have for this product will expire as well.
As stated in [Certified Kubernetes Conformance Program – Terms and Conditions](https://github.com/cncf/k8s-conformance/blob/master/terms-conditions/Certified_Kubernetes_Terms.md#qualifying-offerings-and-self-testing), a Participant’s permission to use the Certified Kubernetes Marks and Participant Kubernetes Combinations with its Qualifying Offerings is time-limited. The Certified Kubernetes Marks and Participant Kubernetes Combinations may be used with a Qualifying Offering for a particular version of Kubernetes (e.g., Kubernetes x.y) until the later of:
12 months after the release date of Kubernetes x.y, or  
9 months after the release date of the next minor release (e.g., Kubernetes x.y+1)
Please make sure to certify your product for Kubernetes v1.22, or v1.23 prior to January 8, in order to have your v1.21 certification remain in effect.
See previous PR submitted to Kubernetes by Daiana - [cncf/k8s-conformance#1776](https://github.com/cncf/k8s-conformance/pull/1776)

**Comment by Aaron-Rob** [comment]
Update received from Kubernetes:

Hello Puppet team,

We’re very pleased that your product was included in our v1.21 Certified Kubernetes offerings. However, unless you have acquired a newer certification for your product, puppetlabs-kubernetes, your Kubernetes v1.21 certification will expire on May 4, 2022.  Any previous certifications you have for this product will expire as well.

As stated in Certified Kubernetes Conformance Program – Terms and Conditions, a Participant’s permission to use the Certified Kubernetes Marks and Participant Kubernetes Combinations with its Qualifying Offerings is time-limited. The Certified Kubernetes Marks and Participant Kubernetes Combinations may be used with a Qualifying Offering for a particular version of Kubernetes (e.g., Kubernetes x.y) until the later of:
12 months after the release date of Kubernetes x.y, or
9 months after the release date of the next minor release (e.g., Kubernetes x.y+1)
v1.21.0 was released on April 8, 2021
https://github.com/kubernetes/kubernetes/releases/tag/v1.21.0

v1.22.0 was released on August 4, 2021
https://github.com/kubernetes/kubernetes/releases/tag/v1.22.0

Therefore, the expiration date for v1.21 is May 4, 2022.

Please make sure to certify your product for Kubernetes v1.22 or v1.23 prior to May 4, in order to have your v1.21 certification remain in effect. Please note that you would also be able to certify for v1.24 once it is released in mid-April 2022.

To view all Certified Kubernetes Distributions & Platforms, please follow this link - https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0.

If you have any questions, please don’t hesitate to reach out.

Thank you,
Taylor Waggoner
Program Manager, CNCF

**Comment by david22swan** [comment]
Guide on confluence:
https://confluence.puppetlabs.com/display/ECO/Sonobuoy+Conformance+Testing+for+the+puppetlabs-kubernetes+module

**Comment by david22swan** [comment]
Kubernetes is now certified: https://github.com/cncf/k8s-conformance/pull/1970
